name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

  
    - name: Install clang & AFL++
      run: sudo apt-get update && sudo apt-get install -y clang afl++



    - name: Install Python deps
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        # editable install so that “import agent” works everywhere
        python -m pip install -e .

    - name: Build targets
      run: |
        make -C targets           # magic_crash
        make -C targets cov       # magic_crash_cov (AFL instrumentation)

    - name: Pytest
      run: python -m pytest -q

